[package]
name = "s3bfg"
version = "0.3.0"
authors = ["Andrew Patterson <andrew@patto.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
hdrhistogram = "*"
http = "*"
httparse = "*"
humansize = "*"
hyper = "*"
futures = "*"
log = "*"
metrics-core = "*"
metrics-runtime = "*"
metrics-util = "*"
native-tls = "*"
nix = "*"
rand = "*"
rayon = "*"
regex = "*"
rusoto_core = "*"
rusoto_credential = "*"
rusoto_s3 = "*"
rusoto_sts = "*"
rustls = "*"
simple-error = "*"
socket2 = "*"
termion = "*"
tokio = { version = "*", features = ["full"] }
tokio-rustls = "*"
trust-dns-client = "*"
tui = "*"
ureq = { version = "*", features = ["json"] }
webpki = "*"
webpki-roots = "*"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "my_benchmark"
harness = false
