[package]
name = "s3zoom"
version = "0.1.0"
authors = ["Andrew Patterson <andrew@patto.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "*"
rayon = "*"
resolve = "*"
hyper = "*"
hyper-tls = "*"
httparse = "*"
progress-streams = "*"
clap = "3.0.0-beta.1"
humansize = "*"
num_cpus = "*"
rand = "*"
tokio = { version = "*", features = ["full"] }
tokio-rustls = "*"
futures = "*"
trust-dns-client = "*"
nix = "*"
webpki = "*"
webpki-roots = "*"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "my_benchmark"
harness = false
